import pandas as pd

df = pd.read_csv('orders.csv')
df['order_date'] = pd.to_datetime(df['order_date'])
df['revenue'] = df['product_price'] * df['quantity']
monthly_revenue = df.groupby(df['order_date'].dt.to_period('M'))['revenue'].sum()
product_revenue = df.groupby('product_name')['revenue'].sum()
customer_revenue = df.groupby('customer_id')['revenue'].sum()
top_customers = customer_revenue.nlargest(10)

print("Total revenue generated by the online store for each month:")
print(monthly_revenue)
print("\nTotal revenue generated by each product:")
print(product_revenue)
print("\nTotal revenue generated by each customer:")
print(customer_revenue)
print("\nTop 10 customers by revenue generated:")
print(top_customers)
