import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('orders.csv')

# Convert the 'order_date' column to datetime format
df['order_date'] = pd.to_datetime(df['order_date'])

# Compute the total revenue generated by the online store for each month
df['revenue'] = df['product_price'] * df['quantity']
monthly_revenue = df.groupby(df['order_date'].dt.to_period('M'))['revenue'].sum()

# Compute the total revenue generated by each product
product_revenue = df.groupby('product_name')['revenue'].sum()

# Compute the total revenue generated by each customer
customer_revenue = df.groupby('customer_id')['revenue'].sum()

# Identify the top 10 customers by revenue generated
top_customers = customer_revenue.nlargest(10)

# Print the results
print("Total revenue generated by the online store for each month:")
print(monthly_revenue)
print("\nTotal revenue generated by each product:")
print(product_revenue)
print("\nTotal revenue generated by each customer:")
print(customer_revenue)
print("\nTop 10 customers by revenue generated:")
print(top_customers)
