import csv
from collections import defaultdict

# read data from the CSV file
with open('orders.csv', 'r') as file:
    reader = csv.DictReader(file)
    orders = list(reader)

# compute total revenue generated by the online store for each month
revenue_by_month = defaultdict(float)
for order in orders:
    order_month = order['order_date'][0:7] # extract year-month from date
    revenue = float(order['product_price']) * int(order['quantity'])
    revenue_by_month[order_month] += revenue

print("Total revenue by month:")
for month, revenue in revenue_by_month.items():
    print(f"{month}: {revenue:.2f}")

# compute total revenue generated by each product
revenue_by_product = defaultdict(float)
for order in orders:
    revenue = float(order['product_price']) * int(order['quantity'])
    revenue_by_product[order['product_name']] += revenue

print("Total revenue by product:")
for product, revenue in revenue_by_product.items():
    print(f"{product}: {revenue:.2f}")

# compute total revenue generated by each customer
revenue_by_customer = defaultdict(float)
for order in orders:
    revenue = float(order['product_price']) * int(order['quantity'])
    revenue_by_customer[order['customer_id']] += revenue

print("Total revenue by customer:")
for customer, revenue in revenue_by_customer.items():
    print(f"{customer}: {revenue:.2f}")

# identify top 10 customers by revenue generated
top_customers = sorted(revenue_by_customer.items(), key=lambda x: x[1], reverse=True)[:10]
print("Top 10 customers by revenue:")
for customer, revenue in top_customers:
    print(f"{customer}: {revenue:.2f}")
