import csv
from collections import defaultdict

# Create dictionaries to store the revenue
revenue_by_month = defaultdict(float)
revenue_by_product = defaultdict(float)
revenue_by_customer = defaultdict(float)

# Read the data from the orders.csv file
with open('orders.csv', 'r') as file:
    reader = csv.DictReader(file)
    for row in reader:
        
        order_date = row['order_date']
        product_name = row['product_name']
        product_price = float(row['product_price'])
        quantity = int(row['quantity'])
        customer_id = row['customer_id']
        
        #revenue generated by the order
        revenue = product_price * quantity
        
        # Updaterevenue dictionaries
        revenue_by_month[order_date[:7]] += revenue
        revenue_by_product[product_name] += revenue
        revenue_by_customer[customer_id] += revenue

#top 10 customers by revenue generated
top_customers = sorted(revenue_by_customer.items(), key=lambda x: x[1], reverse=True)[:10]

# results
print("Total revenue generated by each month:")
for month, revenue in revenue_by_month.items():
    print(f"{month}: {revenue:.2f}")

print("\nTotal revenue generated by each product:")
for product, revenue in revenue_by_product.items():
    print(f"{product}: {revenue:.2f}")

print("\nTotal revenue generated by each customer:")
for customer, revenue in revenue_by_customer.items():
    print(f"{customer}: {revenue:.2f}")

print("\nTop 10 customers by revenue generated:")
for customer, revenue in top_customers:
    print(f"{customer}: {revenue:.2f}")
