import io
import unittest
from unittest.mock import patch

class TestOrderAnalysis(unittest.TestCase):
    
    orders_csv = 'order_id,customer_id,order_date,product_id,product_name,product_price,quantity\n1,A,2022-01-01,1,Product 1,10.0,2\n2,A,2022-01-02,2,Product 2,20.0,1\n3,B,2022-02-01,1,Product 1,10.0,3\n4,C,2022-02-01,3,Product 3,30.0,1\n5,C,2022-03-01,2,Product 2,20.0,2\n'
    
    def test_revenue_by_month(self):
        
        expected_output = "Total revenue generated by each month:\n2022-01: 40.00\n2022-02: 60.00\n2022-03: 40.00\n"
        expected_output_lines = expected_output.split('\n')
        
        with patch('sys.stdout', new=io.StringIO()) as fake_stdout:
            analyze_orders(self.orders_csv)
            output_lines = fake_stdout.getvalue().split('\n')
        
        self.assertEqual(output_lines[:4], expected_output_lines[:4])
    
    def test_revenue_by_product(self):
        
        expected_output = "Total revenue generated by each product:\nProduct 1: 40.00\nProduct 2: 60.00\nProduct 3: 30.00\n"
        expected_output_lines = expected_output.split('\n')
        
        with patch('sys.stdout', new=io.StringIO()) as fake_stdout:
            analyze_orders(self.orders_csv)
            output_lines = fake_stdout.getvalue().split('\n')
      
        self.assertEqual(output_lines[5:8], expected_output_lines[1:4])
    
    def test_revenue_by_customer(self):
       
        expected_output = "Total revenue generated by each customer:\nA: 30.00\nB: 30.00\nC: 90.00\n"
        expected_output_lines = expected_output.split('\n')
      
        with patch('sys.stdout', new=io.StringIO()) as fake_stdout:
            analyze_orders(self.orders_csv)
            output_lines = fake_stdout.getvalue().split('\n')
            
        
        self.assertEqual(output_lines[10:13], expected_output_lines[1:4])
    
    def test_top_customers(self):
        
        expected_output = "Top 10 customers by revenue generated:\nC: 90.00\nA: 30.00\nB: 30.00\n"
        expected_output_lines = expected_output.split('\n')
        
       
        with patch('sys.stdout', new=io.StringIO()) as fake_stdout:
            analyze_orders(self.orders_csv)
            output_lines = fake_stdout.getvalue().split('\n')
        
        self.assertEqual(output_lines[16:19], expected_output_lines[1:4])

if __name__ == '__main__':
    unittest.main()
